### ISSUE TITLE
FLAC playback not working

### ISSUE THREAD

**Issue by stevenroose** [YunoHost-Apps/ampache_ynh#10]
I tried installing the `flac` package from Debian, and I tried uncommenting the line
`transcode_player_webplayer_flac = required`
in the settings.

No idea what to do else..

**Comment by freeplanyo** [comment]
It works for me, I replaced required by allowed in this line https://github.com/YunoHost-Apps/ampache_ynh/blob/master/conf/ampache.cfg.php#L767

Following the Ampache reference here https://github.com/ampache/ampache/wiki/Transcoding
