### ISSUE TITLE
Composer missing, ampache not working

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/ampache_ynh#18]
After fresh install of the app, it's in a non working state, redirecting to some diagnostic page (ampache/test.php) which says that Composer is missing :

>  This tests whether Ampache dependencies are installed.
Please download and install Composer from http://getcomposer.org and install it (e.g: mv composer.phar /usr/local/bin/composer) then run `composer install --prefer-source --no-interaction` on Ampache directory.

FYI my setup is:

```
# yunohost --version
yunohost: 2.4.2
yunohost-admin: 2.4.2
moulinette: 2.4.0.1
ssowat: 2.6.0
```

**Comment by aymhce** [comment]
@JocelynDelalande Can you retry and test an installation since this commit : 1064700722bf2f9d55b61fb723c7aa90be4f7295 please ?

**Comment by JocelynDelalande** [comment]
Tested ; it works.
Thanks a lot !
