### ISSUE TITLE
404 Not Found after installation

### ISSUE THREAD

**Issue by sylvainar** [YunoHost-Apps/ampache_ynh#20]
Hey !

Just after installation, the url domain.tld/ampache/ send back a 404, I have to append `index.php` to the URL to have the page loading. The solution is to enable URL Rewriting parameters in Ampache settings, but maybe it could be solved with nginx only.

Any idea on how to solve this ?

Thanks !

**Comment by aymhce** [comment]
Bad ... I don't have this problem @ home ... But you are the 2nd person to talk me this issue.
Do you have install logs ? What is your Yunohost version ? (I am on 2.7.2)

Do you think ``RewriteEngine On`` is enough ?

**Comment by aymhce** [comment]
@sylvainar I reproduce a 404 on "private navigation" : can you confirm me this : 

With domain.tld/ampache (without slash) there is a 404, but it work on domain.tld/ampache/ (with slash). Right ? (it's that I have an idea of issue's cause)

**Comment by maniackcrudelis** [comment]
Hi, you have to remove the ending slash in the first line of your nginx config file. That's why you have this error.
https://github.com/YunoHost-Apps/ampache_ynh/blob/master/conf/nginx.conf#L1

**Comment by aymhce** [comment]
@maniackcrudelis fix it b52d884b6dc0ffdd0e1241d70f0657522c69dafb
This problem was here a long time ago. Thanks for report.

**Comment by sylvainar** [comment]
Sounds great! I don't have time to retest it today, I'll see tomorrow. Thanks for your reactivity!

**Comment by maniackcrudelis** [comment]
Let's go ;)

**Comment by sylvainar** [comment]
Tested, it works ! 👍 
Thanks for your reactivity !

**Comment by maniackcrudelis** [comment]
Ok, so you should use the helper [`ynh_add_nginx_config`](https://github.com/YunoHost/doc/blob/master/packaging_apps_helpers_fr.md#configuration-syst%C3%A8me).
With this modification, your app doesn't work anymore on root. Nginx failed to reload

**Comment by aymhce** [comment]
@maniackcrudelis ok thanks for advice. But I do an update (a99dd0c1af9475363b32c66e7517e37e6ad0042a) with an homemade method. No more time for implement helper, sorry. It will done later.

Can you retest please ?

**Comment by maniackcrudelis** [comment]
Seems ok now.

**Comment by aymhce** [comment]
I'am consider fixed
