### ISSUE TITLE
Upgrade fails

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/ampache_ynh#26]
Hello @aymhce, the upgrade process fails because of the variable $version which doesn't exist anymore after all helpers use local variables.

So, you have an issue here https://github.com/YunoHost-Apps/ampache_ynh/blob/master/scripts/upgrade#L87

But, my question is, which version number do you really need !?
$version from the helper, as you used before, is the version number from the manifest, https://github.com/YunoHost-Apps/ampache_ynh/blob/master/manifest.json#L8, so 1.0.
But the real version of Ampache that you use is 3.8.3 (according to the [app.src](https://github.com/YunoHost-Apps/ampache_ynh/blob/master/conf/app.src)).
And which file is supposed to be remove by this command ?

**Comment by aymhce** [comment]
Hello, it's about a old portion of code. Forgeted it... Removed now.
