### ISSUE TITLE
Add a default catalog from multimedia directory

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/ampache_ynh#30]
Add a default catalog from `/home/yunohost.multimedia/share/Music`
It's a little bit sad to see that Ampache it's empty whereas this directory is full of music.

Have a look to [ynh_multimedia](https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_multimedia/ynh_multimedia_2)

**Comment by aymhce** [comment]
starting work on https://github.com/aymhce/ampache_ynh/
