### ISSUE TITLE
Update Plex API server 

### ISSUE THREAD

**Issue by miniesta01** [YunoHost-Apps/ampache_ynh#33]
Hello,

I'm currently trying to configure Ampache with Plex. I finally found the link for myPlex server configuration : https://domain.tld/ampache/plex/web/index.php

Authentication and server publication work fine. But on Plex client, I have a message that the serveur is too old... Need at least V1.3.0 (latest plex version is V1.12). Currently Plex server for ampache is V0.9.9.

So my question: how can we upgrade Plex API server in ampache ?

Thanks for your help

++

**Comment by aymhce** [comment]
Hello, you can find api plex version here in the source of ampache : https://github.com/ampache/ampache/blob/c00a6194d5e796d30f2073987df227fcf8998825/lib/class/plex_xml_data.class.php#L188

more informations here : https://github.com/ampache/ampache/wiki/API

I think you can open a issue to Ampache for ask to upgrade api https://github.com/ampache

**Comment by miniesta01** [comment]
Thanks @aymhce. I'll pull my request directly on Ampache project.

**Comment by aymhce** [comment]
You're welcome
