### ISSUE TITLE
Ampache update 4.0.0

### ISSUE THREAD

**Issue by gamersalpha** [YunoHost-Apps/ampache_ynh#39]
Hello there, 

can u please update AMpache 👍 
![image](https://user-images.githubusercontent.com/32466950/48918430-cc95c680-ee8c-11e8-80f1-dc5770799fe9.png)

thanks

**Comment by gamersalpha** [comment]
New update available : 

![image](https://user-images.githubusercontent.com/32466950/49341986-0ae17180-f655-11e8-988e-c1f71bdacd93.png)

**Comment by HugoPoi** [comment]
I think the 4.x is now the official stable with lot of improvement ! If someone can check on that to upgrade this installer it will be great !
