### ISSUE TITLE
Blank page instead of ampache

### ISSUE THREAD

**Issue by 0liUms** [YunoHost-Apps/ampache_ynh#4]
Hi,
I installed Ampache but see nothing but the ampache logo on the title of the tab ( of firefox ).
Don't really know on where to get info on that ? Logs or what ?

thx

liums

**Comment by anmol26s** [comment]
Hi Liums

Add  fastcgi_param SCRIPT_FILENAME $request_filename;  under the line fastcgi_param  PATH_INFO $fastcgi_path_info; in /etc/nginx/conf.d/datamol.in.d/ampache.conf
or 
read this https://forum.yunohost.org/t/problem-with-php-applications-after-upgrade-to-yunohost-2-2/528

Hope it helps.
