### ISSUE TITLE
Change of main maintainer

### ISSUE THREAD

**Issue by aymhce** [YunoHost-Apps/ampache_ynh#42]
Bonjour, ayant peu de disponibilité avec mon emploi du temps, je n'ai plus de possibilité de faire évoluer l'application avec un niveau de qualité satisfaisant. Aussi, et c'est le comble, je n'en suis plus utilisateur, c'était le cas avant et je vois que ça bouge ! Bientôt la version 4 !! Je souhaite passer la main pour continuer à faire vivre cette application exceptionnelle sur Yunohost ! A bientôt ! 

Hello, having little availability with my schedule, I have no more opportunity to upgrade the application with a satisfactory level of quality. Also, I'm not a user anymore, it was the case before and I see that it moves! Soon version 4 !! I wish to pass the hand for this exceptional application can lives on Yunohost! See you soon ! 

Pour info je suis (encore) investi sur l'intégration de Yunohost sur Docker et quelques autres applications...
For information, I am (yet) invested on the integration of Yunohost on Docker and some other applications ...

* https://forum.yunohost.org/t/docker-images-for-yunohost-3/6199
* https://github.com/aymhce/collaboradocker_ynh
* https://github.com/aymhce/diasporadocker_ynh
* https://github.com/aymhce/yunohost_ynh
* https://github.com/YunoHost-Apps/phpldapadmin_ynh

**Comment by gamersalpha** [comment]
bad news, :'(

encore une bonne appli qui devrait etre officiellement supporté (pour moi) qui vas disparaitre du catalogue


....
