### ISSUE TITLE
Can not read songs from the catalog

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/ampache_ynh#5]
I tried to add songs from catalog. I can see the songs but they are not readable by the catalog.
Is there a specific folder that has readable permission for the songs ?

Moreover it requires a ldap to login which do not allow it use as public app. So can it be streamed in third party app or in android phone that way ?

**Comment by aymhce** [comment]
Do you have this issue again ?

**Comment by anmol26s** [comment]
I have not tested it from sometime. I will test it and soon update.

**Comment by aymhce** [comment]
No more news or reports, I'am closing issue
