### ISSUE TITLE
Cannot install (dropbox-sdk repository)

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost-Apps/ampache_ynh#53]
Hi, I cannot install ampache.
The relevant part of the logs seems to be :
```
WARNING -   - git@github.com:dropbox/dropbox-sdk-php.git
WARNING -     Cloning into '/var/www/ampache/lib/vendor/dropbox/dropbox-sdk'...
WARNING -     Permission denied (publickey).
WARNING -     fatal: Could not read from remote repository.
WARNING -     Please make sure you have the correct access rights
WARNING -     and the repository exists.
```
Here's the full log :  https://paste.yunohost.org/raw/roziruboqi

**Comment by maniackcrudelis** [comment]
https://github.com/dropbox/dropbox-sdk-php does not exist anymore.

Nothing to do but to wait for someone to upgrade this package to a more recent version of ampache...

**Comment by HugoPoi** [comment]
Because of this I can't even test #56 , I 'm going to fix this one too.
