### ISSUE TITLE
Error on new install - PHP intl extension

### ISSUE THREAD

**Issue by jose1711** [YunoHost-Apps/ampache_ynh#89]
### Describe the bug

Right after fresh install of `ampache` I get:

![obrázok](https://user-images.githubusercontent.com/1406222/170934349-840ecea4-0b12-4113-b080-d88736f55970.png)

**Comment by ericgaspar** [comment]
This is fixed in testing

**Comment by RhymeInspectah** [comment]
Hi, Ampache 5.4.0 use php8.0 so install php8.0-intl, verify if the intl module is activated in 8.0/cli/conf.d/20-intl.ini (or php.ini, but not the both in same time), enabled with "phpenmod -v 8.0 intl", reload your php server and nginx.
That's done ! update your DB via the ampache invitation and...
Enjoy the latest ynh version of ampache !
Regards

**Comment by jose1711** [comment]
Thank you, all is good now!
